name: tellmeastorymom
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.1.0+9

module:
  androidX: true

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  tel_input: ^0.2.2
  flutter_icons: ^1.1.0
  firebase_storage: ^10.1.0
  expand_widget: ^1.0.0+2
  firebase_analytics: ^8.3.4
  cloud_firestore: ^3.0.0
  firebase_core: ^1.10.0
  flutter_tts:
  shared_preferences:
  share_plus:
  flutter_rating_bar: ^3.0.1+1
  firebase_auth: ^3.2.0
  google_sign_in:
  intl: ^0.17.0
  flutter_svg: ^0.23.0+1
  change_app_package_name: ^0.1.2
  url_launcher:
  image_picker:
  flutter_email_sender: ^5.0.2
  cached_network_image: 3.1.0
  zefyrka: ^1.0.10
  quill_format: ^1.0.2
  firebase_dynamic_links: ^3.0.1
  http:
  path_provider:

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  fonts:
    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
    - family: Poppins-Light
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
    - family: Poppins-Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
    - family: Poppins-Regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: Poppins-SemiBold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
    - family: Poppins-Thin
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
    - family: Oxygen-Regular
      fonts:
        - asset: assets/fonts/Oxygen-Regular.ttf
    - family: Oxygen-Bold
      fonts:
        - asset: assets/fonts/Oxygen-Bold.ttf
